### ISSUE TITLE
Minor error in README.

### ISSUE THREAD

**Issue by gbelwariar** [Microbiome-Diversity-Inspector/Microbiome-Diversity-Inspector#128]
@MAZHARMIK - Can you correct the minor error in README as pointed out in one of the comments here - https://github.com/Microbiome-Diversity-Inspector/Microbiome-Diversity-Inspector/commit/1a80126be8e9e3bb23c27b93bc2c2fdc6232263f?

Thanks.

**Comment by MAZHARMIK** [comment]
Done
