### ISSUE TITLE
Make a copy of this repository and host it on a common Github account.

### ISSUE THREAD

**Issue by gbelwariar** [Microbiome-Diversity-Inspector/Microbiome-Diversity-Inspector#81]
This needs to be done in-order to transfer the ownership from a single owner (currently- @gbelwariar) to all the contributors of this project ([Prof. Malay Bhattacharyya](http://www.iiests.ac.in/index.php/it-malay-bhattacharyya-about), @MAZHARMIK, @gbelwariar) since many of the links may point to this repository in future if successfully published in academic/research websites/papers.

An example of such common account is - https://github.com/angular

@MAZHARMIK - This is not super-urgent right now but we should do this in the near future before any kind of public publications.

**Comment by MAZHARMIK** [comment]
OK sure.

**Comment by gbelwariar** [comment]
This issue has been fixed now.
@MAZHARMIK - I have sent you an invitation to join this organization. Once you will accept the invitation, you will be a part of this organization.
