### ISSUE TITLE
Show the percentage of a task completed and a loading animation while a service is running. 

### ISSUE THREAD

**Issue by gbelwariar** [Microbiome-Diversity-Inspector/Microbiome-Diversity-Inspector#89]
**The issue** - Currently the platform is not user-friendly as the user is kept in dark about the status of his/her tasks running on the platform.

**How to reproduce this issue?** - Use any of the service that requires the user to upload a file, e.g. - real-time entropy analysis etc.

**Note** - This would require a continuous polling by the client to the server to get the real-time status of the running tasks, which might consume computing resources. Thus, this enhancement should not be added at the cost of a slower performance and lagging UI.

**Comment by gbelwariar** [comment]
The addition of a loading animation was done by @MAZHARMIK in https://github.com/Microbiome-Diversity-Inspector/Microbiome-Diversity-Inspector/pull/96 and https://github.com/Microbiome-Diversity-Inspector/Microbiome-Diversity-Inspector/pull/97

**Comment by MAZHARMIK** [comment]
Should I close this issue ?

**Comment by gbelwariar** [comment]
@MAZHARMIK - No don't close this issue, we still have another task left in this issue to be resolved (showing percent completed).

**Comment by gbelwariar** [comment]
@MAZHARMIK - For now I am closing this issue without implementing this feature because of the reason mentioned above (slow and lagging UI). I tried to install multiple `$interval/$timeout` service in my [Pacman game](https://github.com/gbelwariar/Pacman) and at the end it suffered from [this](https://github.com/gbelwariar/Pacman/issues/1) issue.
Although there is a big difference in both the cases as in the Pacman game, I was doing heavy DOM manipulations inside each of the 4-5 `$interval` services which was the reason behind the slow UI, I am afraid that, despite the fact that our UI won't be as laggy as the Pacman one, implementing this feature would still put extra burden on the browser by chewing up all it's resources.
